server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 125728
    name: blog

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.work.blogconsumer.entity

logging:
  level:
    com.work.blogconsumer: debug


