server:
  port: 8002

spring:
  application:
    name: blog-blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 125728
    name: blog

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.work.blogblog.entity

logging:
  level:
    com.work.blogblog: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
