server:
  port: 8082

spring:
  application:
    name: blog-server

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
    fetch-registry: false
    register-with-eureka: false